#######################################################
# This script creates a new R package with RcppArmadillo
#######################################################

# STEP 1: preliminaries
#######################################################
# Put file nicepackage.R in the same folder
# set working directory to the source file location (the same folder)

# STEP 2: create the package
#######################################################
RcppArmadillo::RcppArmadillo.package.skeleton("nicepackage")

# STEP 3: Rproj
#######################################################
# create an R project for the folder "nicepackage"
# open the project, open this file, and just continue


# STEP 4: cleaning
#######################################################
# remove files
file.remove("Read-and-delete-me")
file.remove("src/rcpparma_hello_world.cpp")
file.remove("man/nicepackage-package.Rd")
file.remove("man/rcpparma_hello_world.Rd")

# STEP 5: edit file DESCRIPTION
#######################################################
sink("DESCRIPTION", append = TRUE)
cat("Encoding: UTF-8\n")
sink()

# STEP 6: edit file NAMESPACE
#######################################################
original_lines <- readLines("NAMESPACE")
new_lines <- c("# Generated by roxygen2: do not edit by hand", original_lines[1:2])
writeLines(new_lines, "NAMESPACE")

# STEP 7: use git
#######################################################
usethis::use_git()
# follow the instructions: agree to everything

# STEP 8: include a LICENSE
#######################################################
usethis::use_gpl3_license()

# STEP 9: create package documentation
#######################################################
usethis::use_package_doc()
devtools::document() 

sink("R/nicepackage-package.R")
cat("#' @name nicepackage-package
#' @aliases nicepackage-package nicepackage
#' @docType package
#' @importFrom Rcpp sourceCpp
#' @useDynLib nicepackage, .registration = TRUE
#' @keywords internal
'_PACKAGE'
")
sink()

# STEP 10: include the first C++ files
#######################################################
file.create("src/nicerig2.cpp")
sink("src/nicerig2.cpp")
cat("#include <RcppArmadillo.h>

using namespace Rcpp;
using namespace arma;
\n
// [[Rcpp::export]]
arma::vec nicerig2 (
  const int     n,    // a positive integer - number of draws
  const double  s,    // a positive scale parameter
  const double  nu    // a positive shape parameter
) {
  arma::vec rig2 = s / chi2rnd( nu, n );
  return rig2;
}")
sink()


file.create("src/nicerig2.h")
sink("src/nicerig2.h")
cat("#ifndef _NICERIG_\n
#define _NICERIG_\n
#include <RcppArmadillo.h>\n
arma::vec nicerig2 (
    const int     n,    // a positive integer - number of draws
    const double  s,    // a positive scale parameter
    const double  nu    // a positive shape parameter
);
#endif  // _NICERIG_\n ")
sink()

# STEP 11: roxygenise
#######################################################
roxygen2::roxygenise()

# STEP 12: compile attributes
#######################################################
# to update files src/RcppExports.cpp and R/RcppExports.R
Rcpp::compileAttributes()

# STEP 13: R wrapper for C++ function
#######################################################
file.create("R/nicerig2.R")
sink("R/nicerig2.R")
cat("
#' @title Samples random numbers from the inverted gamma 2 distribution
#' @param n a positive integer number of draws
#' @param s a positive scalar scale parameter
#' @param nu a positive integer shape parameter
#' @return  a vector with \\code{n} independent draws from the inverted gamma 2 distribution
#' @export
nicerig2 <- function(n, s, nu) {
    stopifnot(n > 0 & s > 0 & nu > 0)
    stopifnot(n %% 1 == 0)
    qq = .Call(`_nicepackage_nicerig2`, n, s, nu)
    return(qq)
}\n
")
sink()

# STEP 14: the holly trinity of package checks
#######################################################
Rcpp::compileAttributes()
devtools::document()
devtools::check()

# STEP 15: use your nicepackage
#######################################################
devtools::load_all()
hist(nicerig2(10000, 1, 10), breaks = 100)
?nicerig2
?nicepackage

#######################################################
# YAY! We got it!
#######################################################
# from now on keep developing your package
# after every major change, like an inclusion of a new 
# function in the package, run the following code.
# Run it often and correct for the errors, warnings, 
# and notes straight away.
Rcpp::compileAttributes()
devtools::document()
devtools::check()
